name: "Solix 2 MQTT"
description: "Anker Solix E1600 MQTT integration"
version: "1.5.17"
slug: "solix2mqtt"
init: false
host_network: true
homeassistant_api: true
# hassio_api: true
# hassio_role: admin
map:
  - addons:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  user: ""
  password: ""
  country: "DE"
  mqtt_uri: "mqtt://homeassistant.local:1883"
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "anker/solix"
  poll_interval: 30
schema:
  user: str
  password: password
  country: str
  mqtt_uri: str
  mqtt_username: str
  mqtt_password: password
  mqtt_topic: str
  poll_interval: int
