name: "keyble-mqtt"
description: "Eqiva Smart Lock Bluetooth MQTT"
version: "1.1.8"
slug: "keyble-mqtt"
init: false
host_network: true
host_dbus: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
arch:
  - armv7
options:
  address: ""
  user_id: 0
  user_key: ""
  host: "192.168.0.1"
  username: ""
  password: ""
schema:
  address: str
  user_id: int
  user_key: str
  host: str
  username: str
  password: str
